---
- name: install docker
  hosts: all
  roles:
    - role: geerlingguy.pip
      pip_install_packages:
        - name: docker
          state: absent
        - name: docker-compose
          version: 1.12.0
    - role: geerlingguy.docker
